### ISSUE TITLE
Error installing with python 3.7

### ISSUE THREAD

**Issue by mabitbol** [simonsobs/BBPipe#13]
I get this error when installing BBPipe. I am using python 3.7 and I think the issue is with cwlgen. (I can't install cwlgen with python 3.7). Works fine when I use 3.6. 

(myenv) mabitbol@edison11:~/BBPipe> python setup.py install --user
running install
running bdist_egg
running egg_info
writing BBPipe.egg-info/PKG-INFO
writing dependency_links to BBPipe.egg-info/dependency_links.txt
writing entry points to BBPipe.egg-info/entry_points.txt
writing requirements to BBPipe.egg-info/requires.txt
writing top-level names to BBPipe.egg-info/top_level.txt
reading manifest file 'BBPipe.egg-info/SOURCES.txt'
writing manifest file 'BBPipe.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/bbpipe
copying build/lib/bbpipe/pipeline.py -> build/bdist.linux-x86_64/egg/bbpipe
copying build/lib/bbpipe/stage.py -> build/bdist.linux-x86_64/egg/bbpipe
copying build/lib/bbpipe/__init__.py -> build/bdist.linux-x86_64/egg/bbpipe
copying build/lib/bbpipe/main.py -> build/bdist.linux-x86_64/egg/bbpipe
creating build/bdist.linux-x86_64/egg/bbpipe/sites
copying build/lib/bbpipe/sites/__init__.py -> build/bdist.linux-x86_64/egg/bbpipe/sites
copying build/lib/bbpipe/sites/local.py -> build/bdist.linux-x86_64/egg/bbpipe/sites
byte-compiling build/bdist.linux-x86_64/egg/bbpipe/pipeline.py to pipeline.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/bbpipe/stage.py to stage.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/bbpipe/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/bbpipe/main.py to main.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/bbpipe/sites/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/bbpipe/sites/local.py to local.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying BBPipe.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying BBPipe.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying BBPipe.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying BBPipe.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying BBPipe.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying BBPipe.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
bbpipe.__pycache__.stage.cpython-37: module references __file__
creating 'dist/BBPipe-0.0.5-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing BBPipe-0.0.5-py3.7.egg
removing '/global/u2/m/mabitbol/.local/edison/3.6-anaconda-5.2/lib/python3.7/site-packages/BBPipe-0.0.5-py3.7.egg' (and everything under it)
creating /global/u2/m/mabitbol/.local/edison/3.6-anaconda-5.2/lib/python3.7/site-packages/BBPipe-0.0.5-py3.7.egg
Extracting BBPipe-0.0.5-py3.7.egg to /global/u2/m/mabitbol/.local/edison/3.6-anaconda-5.2/lib/python3.7/site-packages
BBPipe 0.0.5 is already the active version in easy-install.pth
Installing bbpipe script to /global/homes/m/mabitbol/.local/edison/3.6-anaconda-5.2/bin

Installed /global/u2/m/mabitbol/.local/edison/3.6-anaconda-5.2/lib/python3.7/site-packages/BBPipe-0.0.5-py3.7.egg
Processing dependencies for BBPipe==0.0.5
Searching for ruamel.yaml==0.13.13
Reading https://pypi.org/simple/ruamel.yaml/
Downloading https://files.pythonhosted.org/packages/d9/2d/f1773b60c7a78a832f6068761167907302927cb6c7279275a0dcee102e05/ruamel.yaml-0.13.13.tar.gz#sha256=7cfd653648a1d4a635ce7ae254b4dc6ec7df931a5a653c79e627547be5dda71b
Best match: ruamel.yaml 0.13.13
Processing ruamel.yaml-0.13.13.tar.gz
Writing /tmp/easy_install-1ik1vvkf/ruamel.yaml-0.13.13/setup.cfg
Running ruamel.yaml-0.13.13/setup.py -q bdist_egg --dist-dir /tmp/easy_install-1ik1vvkf/ruamel.yaml-0.13.13/egg-dist-tmp-lqbvnfbd
sys.argv ['/tmp/easy_install-1ik1vvkf/ruamel.yaml-0.13.13/setup.py', '-q', 'bdist_egg', '--dist-dir', '/tmp/easy_install-1ik1vvkf/ruamel.yaml-0.13.13/egg-dist-tmp-lqbvnfbd']
test compiling test_ruamel_yaml
Warning: 'keywords' should be a list, got type 'NoneType'
Traceback (most recent call last):
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-1ik1vvkf/ruamel.yaml-0.13.13/setup.py", line 854, in <module>
  File "/tmp/easy_install-1ik1vvkf/ruamel.yaml-0.13.13/setup.py", line 843, in main
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/dist.py", line 370, in __init__
    k: v for k, v in attrs.items()
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/distutils/dist.py", line 267, in __init__
    getattr(self.metadata, "set_" + key)(val)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/distutils/dist.py", line 1203, in set_keywords
    self.keywords = _ensure_list(value, 'keywords')
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/distutils/dist.py", line 40, in _ensure_list
    value = list(value)
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    install_requires=['pyyaml','parsl<0.6.0','cwlgen']
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 415, in run
    self.easy_install(spec, not self.no_deps)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 657, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 704, in install_item
    self.process_distribution(spec, dist, deps)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 749, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 777, in resolve
    replace_conflicting=replace_conflicting
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1060, in best_match
    return self.obtain(req, installer)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1072, in obtain
    return installer(requirement)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 676, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 702, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 887, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1155, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1141, in run_setup
    run_setup(setup_script, args)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-1ik1vvkf/ruamel.yaml-0.13.13/setup.py", line 854, in <module>
  File "/tmp/easy_install-1ik1vvkf/ruamel.yaml-0.13.13/setup.py", line 843, in main
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/site-packages/setuptools/dist.py", line 370, in __init__
    k: v for k, v in attrs.items()
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/distutils/dist.py", line 267, in __init__
    getattr(self.metadata, "set_" + key)(val)
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/distutils/dist.py", line 1203, in set_keywords
    self.keywords = _ensure_list(value, 'keywords')
  File "/global/homes/m/mabitbol/.conda/envs/myenv/lib/python3.7/distutils/dist.py", line 40, in _ensure_list
    value = list(value)
TypeError: 'NoneType' object is not iterable

**Comment by mabitbol** [comment]
If you delete the cwlgen requirement in setup.py you can install using python 3.7. Not sure if we need that?

**Comment by damonge** [comment]
Shall we just get rid of it?
Let me know into where it actually matters (I know we can use it to generate cool workflow plots, but I think that's it).
